dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
env:
  - CODECOV_TOKEN="1384d50e-aaea-4dc0-857c-23a0287ec68b"
# command to run tests
script:
  - pytest --cov=./
  - codecov
